/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPosRouteImport } from './routes/app.pos'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppUsersIndexRouteImport } from './routes/app.users.index'
import { Route as AppSuppliersIndexRouteImport } from './routes/app.suppliers.index'
import { Route as AppStoresIndexRouteImport } from './routes/app.stores.index'
import { Route as AppSalesIndexRouteImport } from './routes/app.sales.index'
import { Route as AppProductsIndexRouteImport } from './routes/app.products.index'
import { Route as AppOrdersIndexRouteImport } from './routes/app.orders.index'
import { Route as AppDebtsIndexRouteImport } from './routes/app.debts.index'
import { Route as AppCustomersIndexRouteImport } from './routes/app.customers.index'
import { Route as AppUsersPermissionsRouteImport } from './routes/app.users.permissions'
import { Route as AppUsersIdRouteImport } from './routes/app.users.$id'
import { Route as AppSuppliersNewRouteImport } from './routes/app.suppliers.new'
import { Route as AppSuppliersIdRouteImport } from './routes/app.suppliers.$id'
import { Route as AppStoresNewRouteImport } from './routes/app.stores.new'
import { Route as AppStoresIdRouteImport } from './routes/app.stores.$id'
import { Route as AppSalesIdRouteImport } from './routes/app.sales.$id'
import { Route as AppProductsNewRouteImport } from './routes/app.products.new'
import { Route as AppProductsCategoriesRouteImport } from './routes/app.products.categories'
import { Route as AppProductsSlugRouteImport } from './routes/app.products.$slug'
import { Route as AppOrdersNewRouteImport } from './routes/app.orders.new'
import { Route as AppOrdersIdRouteImport } from './routes/app.orders.$id'
import { Route as AppInventoryReportsRouteImport } from './routes/app.inventory.reports'
import { Route as AppInventoryMovementsRouteImport } from './routes/app.inventory.movements'
import { Route as AppInventoryCentralRouteImport } from './routes/app.inventory.central'
import { Route as AppInventoryBoutiquesRouteImport } from './routes/app.inventory.boutiques'
import { Route as AppInventoryAdjustmentsRouteImport } from './routes/app.inventory.adjustments'
import { Route as AppCustomersIdRouteImport } from './routes/app.customers.$id'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersIndexRoute = AppSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AppRoute,
} as any)
const AppStoresIndexRoute = AppStoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIndexRoute = AppSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppDebtsIndexRoute = AppDebtsIndexRouteImport.update({
  id: '/debts/',
  path: '/debts/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersPermissionsRoute = AppUsersPermissionsRouteImport.update({
  id: '/users/permissions',
  path: '/users/permissions',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIdRoute = AppUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersNewRoute = AppSuppliersNewRouteImport.update({
  id: '/suppliers/new',
  path: '/suppliers/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersIdRoute = AppSuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppStoresNewRoute = AppStoresNewRouteImport.update({
  id: '/stores/new',
  path: '/stores/new',
  getParentRoute: () => AppRoute,
} as any)
const AppStoresIdRoute = AppStoresIdRouteImport.update({
  id: '/stores/$id',
  path: '/stores/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesIdRoute = AppSalesIdRouteImport.update({
  id: '/sales/$id',
  path: '/sales/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsCategoriesRoute = AppProductsCategoriesRouteImport.update({
  id: '/products/categories',
  path: '/products/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsSlugRoute = AppProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersNewRoute = AppOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryReportsRoute = AppInventoryReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryMovementsRoute = AppInventoryMovementsRouteImport.update({
  id: '/movements',
  path: '/movements',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryCentralRoute = AppInventoryCentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryBoutiquesRoute = AppInventoryBoutiquesRouteImport.update({
  id: '/boutiques',
  path: '/boutiques',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppInventoryAdjustmentsRoute = AppInventoryAdjustmentsRouteImport.update({
  id: '/adjustments',
  path: '/adjustments',
  getParentRoute: () => AppInventoryRoute,
} as any)
const AppCustomersIdRoute = AppCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/help': typeof AppHelpRoute
  '/app/inventory': typeof AppInventoryRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/pos': typeof AppPosRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/customers/$id': typeof AppCustomersIdRoute
  '/app/inventory/adjustments': typeof AppInventoryAdjustmentsRoute
  '/app/inventory/boutiques': typeof AppInventoryBoutiquesRoute
  '/app/inventory/central': typeof AppInventoryCentralRoute
  '/app/inventory/movements': typeof AppInventoryMovementsRoute
  '/app/inventory/reports': typeof AppInventoryReportsRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/orders/new': typeof AppOrdersNewRoute
  '/app/products/$slug': typeof AppProductsSlugRoute
  '/app/products/categories': typeof AppProductsCategoriesRoute
  '/app/products/new': typeof AppProductsNewRoute
  '/app/sales/$id': typeof AppSalesIdRoute
  '/app/stores/$id': typeof AppStoresIdRoute
  '/app/stores/new': typeof AppStoresNewRoute
  '/app/suppliers/$id': typeof AppSuppliersIdRoute
  '/app/suppliers/new': typeof AppSuppliersNewRoute
  '/app/users/$id': typeof AppUsersIdRoute
  '/app/users/permissions': typeof AppUsersPermissionsRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/debts/': typeof AppDebtsIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/sales/': typeof AppSalesIndexRoute
  '/app/stores/': typeof AppStoresIndexRoute
  '/app/suppliers/': typeof AppSuppliersIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/help': typeof AppHelpRoute
  '/app/inventory': typeof AppInventoryRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/pos': typeof AppPosRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/customers/$id': typeof AppCustomersIdRoute
  '/app/inventory/adjustments': typeof AppInventoryAdjustmentsRoute
  '/app/inventory/boutiques': typeof AppInventoryBoutiquesRoute
  '/app/inventory/central': typeof AppInventoryCentralRoute
  '/app/inventory/movements': typeof AppInventoryMovementsRoute
  '/app/inventory/reports': typeof AppInventoryReportsRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/orders/new': typeof AppOrdersNewRoute
  '/app/products/$slug': typeof AppProductsSlugRoute
  '/app/products/categories': typeof AppProductsCategoriesRoute
  '/app/products/new': typeof AppProductsNewRoute
  '/app/sales/$id': typeof AppSalesIdRoute
  '/app/stores/$id': typeof AppStoresIdRoute
  '/app/stores/new': typeof AppStoresNewRoute
  '/app/suppliers/$id': typeof AppSuppliersIdRoute
  '/app/suppliers/new': typeof AppSuppliersNewRoute
  '/app/users/$id': typeof AppUsersIdRoute
  '/app/users/permissions': typeof AppUsersPermissionsRoute
  '/app/customers': typeof AppCustomersIndexRoute
  '/app/debts': typeof AppDebtsIndexRoute
  '/app/orders': typeof AppOrdersIndexRoute
  '/app/products': typeof AppProductsIndexRoute
  '/app/sales': typeof AppSalesIndexRoute
  '/app/stores': typeof AppStoresIndexRoute
  '/app/suppliers': typeof AppSuppliersIndexRoute
  '/app/users': typeof AppUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/help': typeof AppHelpRoute
  '/app/inventory': typeof AppInventoryRouteWithChildren
  '/app/notifications': typeof AppNotificationsRoute
  '/app/pos': typeof AppPosRoute
  '/app/profile': typeof AppProfileRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/customers/$id': typeof AppCustomersIdRoute
  '/app/inventory/adjustments': typeof AppInventoryAdjustmentsRoute
  '/app/inventory/boutiques': typeof AppInventoryBoutiquesRoute
  '/app/inventory/central': typeof AppInventoryCentralRoute
  '/app/inventory/movements': typeof AppInventoryMovementsRoute
  '/app/inventory/reports': typeof AppInventoryReportsRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/app/orders/new': typeof AppOrdersNewRoute
  '/app/products/$slug': typeof AppProductsSlugRoute
  '/app/products/categories': typeof AppProductsCategoriesRoute
  '/app/products/new': typeof AppProductsNewRoute
  '/app/sales/$id': typeof AppSalesIdRoute
  '/app/stores/$id': typeof AppStoresIdRoute
  '/app/stores/new': typeof AppStoresNewRoute
  '/app/suppliers/$id': typeof AppSuppliersIdRoute
  '/app/suppliers/new': typeof AppSuppliersNewRoute
  '/app/users/$id': typeof AppUsersIdRoute
  '/app/users/permissions': typeof AppUsersPermissionsRoute
  '/app/customers/': typeof AppCustomersIndexRoute
  '/app/debts/': typeof AppDebtsIndexRoute
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/sales/': typeof AppSalesIndexRoute
  '/app/stores/': typeof AppStoresIndexRoute
  '/app/suppliers/': typeof AppSuppliersIndexRoute
  '/app/users/': typeof AppUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/verify-email'
    | '/app/expenses'
    | '/app/help'
    | '/app/inventory'
    | '/app/notifications'
    | '/app/pos'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/'
    | '/app/customers/$id'
    | '/app/inventory/adjustments'
    | '/app/inventory/boutiques'
    | '/app/inventory/central'
    | '/app/inventory/movements'
    | '/app/inventory/reports'
    | '/app/orders/$id'
    | '/app/orders/new'
    | '/app/products/$slug'
    | '/app/products/categories'
    | '/app/products/new'
    | '/app/sales/$id'
    | '/app/stores/$id'
    | '/app/stores/new'
    | '/app/suppliers/$id'
    | '/app/suppliers/new'
    | '/app/users/$id'
    | '/app/users/permissions'
    | '/app/customers/'
    | '/app/debts/'
    | '/app/orders/'
    | '/app/products/'
    | '/app/sales/'
    | '/app/stores/'
    | '/app/suppliers/'
    | '/app/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/verify-email'
    | '/app/expenses'
    | '/app/help'
    | '/app/inventory'
    | '/app/notifications'
    | '/app/pos'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app'
    | '/app/customers/$id'
    | '/app/inventory/adjustments'
    | '/app/inventory/boutiques'
    | '/app/inventory/central'
    | '/app/inventory/movements'
    | '/app/inventory/reports'
    | '/app/orders/$id'
    | '/app/orders/new'
    | '/app/products/$slug'
    | '/app/products/categories'
    | '/app/products/new'
    | '/app/sales/$id'
    | '/app/stores/$id'
    | '/app/stores/new'
    | '/app/suppliers/$id'
    | '/app/suppliers/new'
    | '/app/users/$id'
    | '/app/users/permissions'
    | '/app/customers'
    | '/app/debts'
    | '/app/orders'
    | '/app/products'
    | '/app/sales'
    | '/app/stores'
    | '/app/suppliers'
    | '/app/users'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/change-password'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/verify-email'
    | '/app/expenses'
    | '/app/help'
    | '/app/inventory'
    | '/app/notifications'
    | '/app/pos'
    | '/app/profile'
    | '/app/reports'
    | '/app/settings'
    | '/app/'
    | '/app/customers/$id'
    | '/app/inventory/adjustments'
    | '/app/inventory/boutiques'
    | '/app/inventory/central'
    | '/app/inventory/movements'
    | '/app/inventory/reports'
    | '/app/orders/$id'
    | '/app/orders/new'
    | '/app/products/$slug'
    | '/app/products/categories'
    | '/app/products/new'
    | '/app/sales/$id'
    | '/app/stores/$id'
    | '/app/stores/new'
    | '/app/suppliers/$id'
    | '/app/suppliers/new'
    | '/app/users/$id'
    | '/app/users/permissions'
    | '/app/customers/'
    | '/app/debts/'
    | '/app/orders/'
    | '/app/products/'
    | '/app/sales/'
    | '/app/stores/'
    | '/app/suppliers/'
    | '/app/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pos': {
      id: '/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users/': {
      id: '/app/users/'
      path: '/users'
      fullPath: '/app/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers/': {
      id: '/app/suppliers/'
      path: '/suppliers'
      fullPath: '/app/suppliers/'
      preLoaderRoute: typeof AppSuppliersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stores/': {
      id: '/app/stores/'
      path: '/stores'
      fullPath: '/app/stores/'
      preLoaderRoute: typeof AppStoresIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales/': {
      id: '/app/sales/'
      path: '/sales'
      fullPath: '/app/sales/'
      preLoaderRoute: typeof AppSalesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products/': {
      id: '/app/products/'
      path: '/products'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders/': {
      id: '/app/orders/'
      path: '/orders'
      fullPath: '/app/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/debts/': {
      id: '/app/debts/'
      path: '/debts'
      fullPath: '/app/debts/'
      preLoaderRoute: typeof AppDebtsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/customers/': {
      id: '/app/customers/'
      path: '/customers'
      fullPath: '/app/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users/permissions': {
      id: '/app/users/permissions'
      path: '/users/permissions'
      fullPath: '/app/users/permissions'
      preLoaderRoute: typeof AppUsersPermissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/users/$id': {
      id: '/app/users/$id'
      path: '/users/$id'
      fullPath: '/app/users/$id'
      preLoaderRoute: typeof AppUsersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers/new': {
      id: '/app/suppliers/new'
      path: '/suppliers/new'
      fullPath: '/app/suppliers/new'
      preLoaderRoute: typeof AppSuppliersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers/$id': {
      id: '/app/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/app/suppliers/$id'
      preLoaderRoute: typeof AppSuppliersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stores/new': {
      id: '/app/stores/new'
      path: '/stores/new'
      fullPath: '/app/stores/new'
      preLoaderRoute: typeof AppStoresNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stores/$id': {
      id: '/app/stores/$id'
      path: '/stores/$id'
      fullPath: '/app/stores/$id'
      preLoaderRoute: typeof AppStoresIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/sales/$id': {
      id: '/app/sales/$id'
      path: '/sales/$id'
      fullPath: '/app/sales/$id'
      preLoaderRoute: typeof AppSalesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products/new': {
      id: '/app/products/new'
      path: '/products/new'
      fullPath: '/app/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products/categories': {
      id: '/app/products/categories'
      path: '/products/categories'
      fullPath: '/app/products/categories'
      preLoaderRoute: typeof AppProductsCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products/$slug': {
      id: '/app/products/$slug'
      path: '/products/$slug'
      fullPath: '/app/products/$slug'
      preLoaderRoute: typeof AppProductsSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders/new': {
      id: '/app/orders/new'
      path: '/orders/new'
      fullPath: '/app/orders/new'
      preLoaderRoute: typeof AppOrdersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders/$id': {
      id: '/app/orders/$id'
      path: '/orders/$id'
      fullPath: '/app/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory/reports': {
      id: '/app/inventory/reports'
      path: '/reports'
      fullPath: '/app/inventory/reports'
      preLoaderRoute: typeof AppInventoryReportsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/movements': {
      id: '/app/inventory/movements'
      path: '/movements'
      fullPath: '/app/inventory/movements'
      preLoaderRoute: typeof AppInventoryMovementsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/central': {
      id: '/app/inventory/central'
      path: '/central'
      fullPath: '/app/inventory/central'
      preLoaderRoute: typeof AppInventoryCentralRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/boutiques': {
      id: '/app/inventory/boutiques'
      path: '/boutiques'
      fullPath: '/app/inventory/boutiques'
      preLoaderRoute: typeof AppInventoryBoutiquesRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/inventory/adjustments': {
      id: '/app/inventory/adjustments'
      path: '/adjustments'
      fullPath: '/app/inventory/adjustments'
      preLoaderRoute: typeof AppInventoryAdjustmentsRouteImport
      parentRoute: typeof AppInventoryRoute
    }
    '/app/customers/$id': {
      id: '/app/customers/$id'
      path: '/customers/$id'
      fullPath: '/app/customers/$id'
      preLoaderRoute: typeof AppCustomersIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppInventoryRouteChildren {
  AppInventoryAdjustmentsRoute: typeof AppInventoryAdjustmentsRoute
  AppInventoryBoutiquesRoute: typeof AppInventoryBoutiquesRoute
  AppInventoryCentralRoute: typeof AppInventoryCentralRoute
  AppInventoryMovementsRoute: typeof AppInventoryMovementsRoute
  AppInventoryReportsRoute: typeof AppInventoryReportsRoute
}

const AppInventoryRouteChildren: AppInventoryRouteChildren = {
  AppInventoryAdjustmentsRoute: AppInventoryAdjustmentsRoute,
  AppInventoryBoutiquesRoute: AppInventoryBoutiquesRoute,
  AppInventoryCentralRoute: AppInventoryCentralRoute,
  AppInventoryMovementsRoute: AppInventoryMovementsRoute,
  AppInventoryReportsRoute: AppInventoryReportsRoute,
}

const AppInventoryRouteWithChildren = AppInventoryRoute._addFileChildren(
  AppInventoryRouteChildren,
)

interface AppRouteChildren {
  AppExpensesRoute: typeof AppExpensesRoute
  AppHelpRoute: typeof AppHelpRoute
  AppInventoryRoute: typeof AppInventoryRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPosRoute: typeof AppPosRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCustomersIdRoute: typeof AppCustomersIdRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppOrdersNewRoute: typeof AppOrdersNewRoute
  AppProductsSlugRoute: typeof AppProductsSlugRoute
  AppProductsCategoriesRoute: typeof AppProductsCategoriesRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppSalesIdRoute: typeof AppSalesIdRoute
  AppStoresIdRoute: typeof AppStoresIdRoute
  AppStoresNewRoute: typeof AppStoresNewRoute
  AppSuppliersIdRoute: typeof AppSuppliersIdRoute
  AppSuppliersNewRoute: typeof AppSuppliersNewRoute
  AppUsersIdRoute: typeof AppUsersIdRoute
  AppUsersPermissionsRoute: typeof AppUsersPermissionsRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppDebtsIndexRoute: typeof AppDebtsIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppSalesIndexRoute: typeof AppSalesIndexRoute
  AppStoresIndexRoute: typeof AppStoresIndexRoute
  AppSuppliersIndexRoute: typeof AppSuppliersIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppExpensesRoute: AppExpensesRoute,
  AppHelpRoute: AppHelpRoute,
  AppInventoryRoute: AppInventoryRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPosRoute: AppPosRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCustomersIdRoute: AppCustomersIdRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppOrdersNewRoute: AppOrdersNewRoute,
  AppProductsSlugRoute: AppProductsSlugRoute,
  AppProductsCategoriesRoute: AppProductsCategoriesRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppSalesIdRoute: AppSalesIdRoute,
  AppStoresIdRoute: AppStoresIdRoute,
  AppStoresNewRoute: AppStoresNewRoute,
  AppSuppliersIdRoute: AppSuppliersIdRoute,
  AppSuppliersNewRoute: AppSuppliersNewRoute,
  AppUsersIdRoute: AppUsersIdRoute,
  AppUsersPermissionsRoute: AppUsersPermissionsRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppDebtsIndexRoute: AppDebtsIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppSalesIndexRoute: AppSalesIndexRoute,
  AppStoresIndexRoute: AppStoresIndexRoute,
  AppSuppliersIndexRoute: AppSuppliersIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
